# Generated by Django 6.0.2 on 2026-09-13 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="assigned_members",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_project", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
